version: '3.3'

services:
  web:
    build:
      context: ./djapp
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 djapp.wsgi:application
    volumes:
      - ./static:/home/static
      - ./media:/home/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
 
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - ./static:/home/djapp/static
      - ./media:/home/djapp/media
    expose:
      - 80
    ports:
      - 1337:80
    restart: always
    depends_on:
      - web
