# Generated by Django 3.1.5 on 2021-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.JSONField(db_column='answers', help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='date', help_text='Дата и время ответов.', verbose_name='Дата и время ответов:'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_name',
            field=models.TextField(db_column='name', help_text='Имя пользователя.', verbose_name='Имя пользователя:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.TextField(db_column='answer1', help_text='Ответ номер - 1.', verbose_name='Ответ номер - 1:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(db_column='answer2', help_text='Ответ номер - 2.', verbose_name='Ответ номер - 2:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.TextField(db_column='answer3', help_text='Ответ номер - 3.', verbose_name='Ответ номер - 3:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(db_column='number', help_text='Номер вопроса.', verbose_name='Номер вопроса:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(db_column='text', help_text='Текст вопроса.', verbose_name='Текст вопроса:'),
        ),
    ]
