# Generated by Django 3.1.5 on 2021-01-07 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210104_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='date',
        ),
        migrations.AddField(
            model_name='answer',
            name='end_testing_dtime',
            field=models.DateTimeField(db_column='end_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время окончания тестирования.', verbose_name='Дата и время окончания тестирования:'),
        ),
        migrations.AddField(
            model_name='answer',
            name='first_name',
            field=models.TextField(db_column='first_name', default='NoFirstName', help_text='Имя.', max_length=20, verbose_name='Имя:'),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_name',
            field=models.TextField(db_column='last_name', default='NoLastName', help_text='Фамилия.', max_length=20, verbose_name='Фамилия:'),
        ),
        migrations.AddField(
            model_name='answer',
            name='patronymic',
            field=models.TextField(db_column='patronymic', default='NoPatronymic', help_text='Отчество.', max_length=20, verbose_name='Отчество:'),
        ),
        migrations.AddField(
            model_name='answer',
            name='start_testing_dtime',
            field=models.DateTimeField(db_column='start_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время начала тестирования.', verbose_name='Дата и время начала тестирования:'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_name',
            field=models.TextField(db_column='name', default='NoName', help_text='Имя пользователя.', max_length=20, verbose_name='Имя пользователя:'),
        ),
    ]
