# Generated by Django 3.1.5 on 2021-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210107_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='user_id', help_text='Идентификатор пользователя.', verbose_name='Идентификатор пользователя:')),
                ('available_tests', models.JSONField(db_column='available_tests', help_text='Список доступных для пользователя тестов и отметка о их прохождении:', verbose_name='Список доступных для пользователя тестов и отметка о их прохождении:')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='KettellAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='KettellQuestion',
        ),
    ]
