# Generated by Django 3.1.5 on 2021-01-19 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0005_auto_20210119_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationtestuser',
            name='available_tests',
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
