# Generated by Django 3.1.5 on 2021-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20210119_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtestuser',
            name='available_tests',
            field=models.JSONField(db_column='available_tests', default='', help_text='Список доступных для пользователя тестов и отметка о их прохождении:', verbose_name='Список доступных для пользователя тестов и отметка о их прохождении:'),
        ),
    ]
