# Generated by Django 3.1.5 on 2021-01-19 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0008_auto_20210119_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationtestuser',
            name='available_tests',
            field=models.JSONField(db_column='available_tests', default={}, help_text='Список доступных для пользователя тестов и отметка о их прохождении:', verbose_name='Список доступных для пользователя тестов и отметка о их прохождении:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='first_name',
            field=models.TextField(db_column='first_name', default='', help_text='Имя.', max_length=20, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='last_name',
            field=models.TextField(db_column='last_name', default='', help_text='Фамилия.', max_length=20, verbose_name='Фамилия:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='patronymic',
            field=models.TextField(db_column='patronymic', default='', help_text='Отчество.', max_length=20, verbose_name='Отчество:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Идентификатор пользователя:'),
        ),
    ]
