# Generated by Django 3.1.5 on 2021-01-23 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20210119_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPIQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', help_text='Номер вопроса.', verbose_name='Номер вопроса:')),
                ('question', models.TextField(db_column='text', help_text='Текст вопроса.', verbose_name='Текст вопроса:')),
                ('gender', models.IntegerField(db_column='gender', help_text='Признак половой принадлежности вопроса.', verbose_name='Признак половой принадлежности вопроса:')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SCLQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', help_text='Номер вопроса.', verbose_name='Номер вопроса:')),
                ('question', models.TextField(db_column='text', help_text='Текст вопроса.', verbose_name='Текст вопроса:')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RemoveField(
            model_name='kettellanswer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='kettellanswer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='kettellanswer',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='kettellanswer',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='kettellanswer',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, to='tests.informationtestuser', verbose_name='Идентификатор пользователя:'),
        ),
        migrations.CreateModel(
            name='SCLAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_testing_dtime', models.DateTimeField(db_column='start_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время начала тестирования.', verbose_name='Дата и время начала тестирования:')),
                ('end_testing_dtime', models.DateTimeField(db_column='end_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время окончания тестирования.', verbose_name='Дата и время окончания тестирования:')),
                ('answers', models.JSONField(db_column='answers', help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, to='tests.informationtestuser', verbose_name='Идентификатор пользователя:')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MMPIAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_testing_dtime', models.DateTimeField(db_column='start_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время начала тестирования.', verbose_name='Дата и время начала тестирования:')),
                ('end_testing_dtime', models.DateTimeField(db_column='end_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время окончания тестирования.', verbose_name='Дата и время окончания тестирования:')),
                ('answers', models.JSONField(db_column='answers', help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, to='tests.informationtestuser', verbose_name='Идентификатор пользователя:')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
