# Generated by Django 3.1.5 on 2021-01-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20210123_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtestuser',
            name='gender',
            field=models.IntegerField(db_column='gender', default=1, help_text='Пол пользователя.', verbose_name='Пол пользователя:'),
        ),
    ]
