# Generated by Django 3.1.5 on 2021-01-28 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20210125_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSafetyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', help_text='Номер вопроса.', verbose_name='Номер вопроса:')),
                ('question', models.TextField(db_column='text', help_text='Текст вопроса.', verbose_name='Текст вопроса:')),
                ('answer_1', models.TextField(db_column='answer1', help_text='Ответ номер - 1.', verbose_name='Ответ номер - 1:')),
                ('answer_2', models.TextField(db_column='answer2', help_text='Ответ номер - 2.', verbose_name='Ответ номер - 2:')),
                ('answer_3', models.TextField(db_column='answer3', help_text='Ответ номер - 3.', verbose_name='Ответ номер - 3:')),
                ('answer_4', models.TextField(db_column='answer4', help_text='Ответ номер - 4.', verbose_name='Ответ номер - 4:')),
                ('correct_answer', models.IntegerField(db_column='correct_answer', help_text='Номер правильного ответа.', verbose_name='Номер правильного ответа:')),
            ],
            options={
                'verbose_name': 'вопрос теста для подразделений транспортной безопасности',
                'verbose_name_plural': 'Вопросы теста для подразделений транспортной безопасности',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TSafetyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_testing_dtime', models.DateTimeField(db_column='start_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время начала тестирования.', verbose_name='Дата и время начала тестирования:')),
                ('end_testing_dtime', models.DateTimeField(db_column='end_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время окончания тестирования.', verbose_name='Дата и время окончания тестирования:')),
                ('answers', models.JSONField(db_column='answers', help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, to='tests.informationtestuser', verbose_name='Идентификатор пользователя:')),
            ],
            options={
                'verbose_name': 'ответ теста для подразделений транспортной безопасности',
                'verbose_name_plural': 'Ответы теста для подразделений транспортной безопасности',
                'ordering': ['-id'],
            },
        ),
    ]
