# Generated by Django 3.1.5 on 2021-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_tsafetyanswer_tsafetyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmpiquestion',
            name='noise',
            field=models.IntegerField(db_column='noise', default=0, help_text='Отметка о неучете ответа на данный вопрос.', verbose_name='Отметка о неучете ответа на данный вопрос:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_1',
            field=models.IntegerField(db_column='scale_1', default=0, help_text='Значение правильного ответа по шкале - 1.', verbose_name='Значение правильного ответа по шкале - 1:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_10',
            field=models.IntegerField(db_column='scale_10', default=0, help_text='Значение правильного ответа по шкале - 10.', verbose_name='Значение правильного ответа по шкале - 10:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_2',
            field=models.IntegerField(db_column='scale_2', default=0, help_text='Значение правильного ответа по шкале - 2.', verbose_name='Значение правильного ответа по шкале - 2:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_3',
            field=models.IntegerField(db_column='scale_3', default=0, help_text='Значение правильного ответа по шкале - 3.', verbose_name='Значение правильного ответа по шкале - 3:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_4',
            field=models.IntegerField(db_column='scale_4', default=0, help_text='Значение правильного ответа по шкале - 4.', verbose_name='Значение правильного ответа по шкале - 4:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_5',
            field=models.IntegerField(db_column='scale_5', default=0, help_text='Значение правильного ответа по шкале - 5.', verbose_name='Значение правильного ответа по шкале - 5:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_6',
            field=models.IntegerField(db_column='scale_6', default=0, help_text='Значение правильного ответа по шкале - 6.', verbose_name='Значение правильного ответа по шкале - 6:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_7',
            field=models.IntegerField(db_column='scale_7', default=0, help_text='Значение правильного ответа по шкале - 7.', verbose_name='Значение правильного ответа по шкале - 7:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_8',
            field=models.IntegerField(db_column='scale_8', default=0, help_text='Значение правильного ответа по шкале - 8.', verbose_name='Значение правильного ответа по шкале - 8:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_9',
            field=models.IntegerField(db_column='scale_9', default=0, help_text='Значение правильного ответа по шкале - 9.', verbose_name='Значение правильного ответа по шкале - 9:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_F',
            field=models.IntegerField(db_column='scale_f', default=0, help_text='Значение правильного ответа по шкале - F.', verbose_name='Значение правильного ответа по шкале - F:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_K',
            field=models.IntegerField(db_column='scale_k', default=0, help_text='Значение правильного ответа по шкале - K.', verbose_name='Значение правильного ответа по шкале - K:'),
        ),
        migrations.AddField(
            model_name='mmpiquestion',
            name='scale_L',
            field=models.IntegerField(db_column='scale_l', default=0, help_text='Значение правильного ответа по шкале - L.', verbose_name='Значение правильного ответа по шкале - L:'),
        ),
    ]
