# Generated by Django 3.1.5 on 2021-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20210201_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsafetyanswer',
            name='results',
            field=models.JSONField(db_column='results', default=dict, help_text='Результаты обработки ответов.', verbose_name='Результаты обработки ответов:'),
        ),
        migrations.AlterField(
            model_name='kettellanswer',
            name='answers',
            field=models.JSONField(db_column='answers', default=dict, help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:'),
        ),
        migrations.AlterField(
            model_name='mmpianswer',
            name='answers',
            field=models.JSONField(db_column='answers', default=dict, help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:'),
        ),
        migrations.AlterField(
            model_name='sclanswer',
            name='answers',
            field=models.JSONField(db_column='answers', default=dict, help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:'),
        ),
        migrations.AlterField(
            model_name='tsafetyanswer',
            name='answers',
            field=models.JSONField(db_column='answers', default=dict, help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:'),
        ),
    ]
