# Generated by Django 3.1.5 on 2021-02-15 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_mmpianswer_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPMQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', help_text='Номер вопроса.', verbose_name='Номер вопроса:')),
                ('question_img', models.ImageField(db_column='question_img', help_text='Изображение вопроса.', upload_to='', verbose_name='Изображение вопроса:')),
                ('answer_img_1', models.ImageField(db_column='answer_img_1', help_text='Изображение ответа-1.', upload_to='', verbose_name='Изображение ответа-1:')),
                ('answer_img_2', models.ImageField(db_column='answer_img_2', help_text='Изображение ответа-2.', upload_to='', verbose_name='Изображение ответа-2:')),
                ('answer_img_3', models.ImageField(db_column='answer_img_3', help_text='Изображение ответа-3.', upload_to='', verbose_name='Изображение ответа-3:')),
                ('answer_img_4', models.ImageField(db_column='answer_img_4', help_text='Изображение ответа-4.', upload_to='', verbose_name='Изображение ответа-4:')),
                ('answer_img_5', models.ImageField(db_column='answer_img_5', help_text='Изображение ответа-5.', upload_to='', verbose_name='Изображение ответа-5:')),
                ('answer_img_6', models.ImageField(db_column='answer_img_6', help_text='Изображение ответа-6.', upload_to='', verbose_name='Изображение ответа-6:')),
                ('answer_img_7', models.ImageField(db_column='answer_img_7', help_text='Изображение ответа-7.', upload_to='', verbose_name='Изображение ответа-7:')),
                ('answer_img_8', models.ImageField(db_column='answer_img_8', help_text='Изображение ответа-8.', upload_to='', verbose_name='Изображение ответа-8:')),
            ],
            options={
                'verbose_name': 'вопрос теста прогрессивных матриц Равена',
                'verbose_name_plural': 'Вопросы теста прогрессивных матриц Равена',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RPMAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_testing_dtime', models.DateTimeField(db_column='start_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время начала тестирования.', verbose_name='Дата и время начала тестирования:')),
                ('end_testing_dtime', models.DateTimeField(db_column='end_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время окончания тестирования.', verbose_name='Дата и время окончания тестирования:')),
                ('answers', models.JSONField(db_column='answers', default=dict, help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, to='tests.informationtestuser', verbose_name='Идентификатор пользователя:')),
            ],
            options={
                'verbose_name': 'ответ теста прогрессивных матриц Равена',
                'verbose_name_plural': 'Ответы теста прогрессивных матриц Равена',
                'ordering': ['-id'],
            },
        ),
    ]
