# Generated by Django 3.1.5 on 2021-02-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_rpmanswer_rpmquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmquestion',
            name='group',
            field=models.CharField(blank=True, db_column='group', help_text='Группа вопроса и его номер в группе.', max_length=5, verbose_name='Группа вопроса и его номер в группе:'),
        ),
        migrations.AlterField(
            model_name='rpmquestion',
            name='answer_img_7',
            field=models.ImageField(blank=True, db_column='answer_img_7', help_text='Изображение ответа-7.', upload_to='', verbose_name='Изображение ответа-7:'),
        ),
        migrations.AlterField(
            model_name='rpmquestion',
            name='answer_img_8',
            field=models.ImageField(blank=True, db_column='answer_img_8', help_text='Изображение ответа-8.', upload_to='', verbose_name='Изображение ответа-8:'),
        ),
    ]
