# Generated by Django 3.1.5 on 2021-02-17 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_rpmanswer_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComAnalogQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='number', help_text='Номер вопроса.', verbose_name='Номер вопроса:')),
                ('question', models.TextField(db_column='text', help_text='Текст вопроса.', verbose_name='Текст вопроса:')),
                ('correct_answer', models.CharField(db_column='correct_answer', default='A', help_text='Буква правильного ответа.', max_length=5, verbose_name='Буква правильного ответа:')),
            ],
            options={
                'verbose_name': 'вопрос теста сложных аналогий',
                'verbose_name_plural': 'Вопросы теста сложных аналогий',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ComAnalogAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_testing_dtime', models.DateTimeField(db_column='start_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время начала тестирования.', verbose_name='Дата и время начала тестирования:')),
                ('end_testing_dtime', models.DateTimeField(db_column='end_testing_dtime', default=django.utils.timezone.now, help_text='Дата и время окончания тестирования.', verbose_name='Дата и время окончания тестирования:')),
                ('answers', models.JSONField(db_column='answers', default=dict, help_text='Данные пользователем ответы (в формате JSON).', verbose_name='Ответы:')),
                ('results', models.JSONField(db_column='results', default=dict, help_text='Результаты обработки ответов.', verbose_name='Результаты обработки ответов:')),
                ('user_id', models.ForeignKey(db_column='user_id', help_text='Идентификатор пользователя.', on_delete=django.db.models.deletion.CASCADE, to='tests.informationtestuser', verbose_name='Идентификатор пользователя:')),
            ],
            options={
                'verbose_name': 'ответ теста сложных аналогий',
                'verbose_name_plural': 'Ответы теста сложных аналогий',
                'ordering': ['-id'],
            },
        ),
    ]
