# Generated by Django 3.1.5 on 2021-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_comanaloganswer_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_A',
            field=models.CharField(db_column='factor_A', default=0, help_text='Значения правильных ответов по фактору - A.', max_length=2, verbose_name='Значения правильных ответов по фактору - A:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_B',
            field=models.CharField(db_column='factor_B', default=0, help_text='Значение правильного ответа по фактору - B.', max_length=1, verbose_name='Значение правильного ответа по фактору - B:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_C',
            field=models.CharField(db_column='factor_C', default=0, help_text='Значения правильных ответов по фактору - C.', max_length=2, verbose_name='Значения правильных ответов по фактору - C:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_E',
            field=models.CharField(db_column='factor_E', default=0, help_text='Значения правильных ответов по фактору - E.', max_length=2, verbose_name='Значения правильных ответов по фактору - E:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_F',
            field=models.CharField(db_column='factor_F', default=0, help_text='Значения правильных ответов по фактору - F.', max_length=2, verbose_name='Значения правильных ответов по фактору - F:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_G',
            field=models.CharField(db_column='factor_G', default=0, help_text='Значения правильных ответов по фактору - G.', max_length=2, verbose_name='Значения правильных ответов по фактору - G:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_H',
            field=models.CharField(db_column='factor_H', default=0, help_text='Значения правильных ответов по фактору - H.', max_length=2, verbose_name='Значения правильных ответов по фактору - H:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_I',
            field=models.CharField(db_column='factor_I', default=0, help_text='Значения правильных ответов по фактору - I.', max_length=2, verbose_name='Значения правильных ответов по фактору - I:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_L',
            field=models.CharField(db_column='factor_L', default=0, help_text='Значения правильных ответов по фактору - L.', max_length=2, verbose_name='Значения правильных ответов по фактору - L:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_M',
            field=models.CharField(db_column='factor_M', default=0, help_text='Значения правильных ответов по фактору - M.', max_length=2, verbose_name='Значения правильных ответов по фактору - M:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_N',
            field=models.CharField(db_column='factor_N', default=0, help_text='Значения правильных ответов по фактору - N.', max_length=2, verbose_name='Значения правильных ответов по фактору - N:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_O',
            field=models.CharField(db_column='factor_O', default=0, help_text='Значения правильных ответов по фактору - O.', max_length=2, verbose_name='Значения правильных ответов по фактору - O:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_Q1',
            field=models.CharField(db_column='factor_Q1', default=0, help_text='Значения правильных ответов по фактору - Q1.', max_length=2, verbose_name='Значения правильных ответов по фактору - Q1:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_Q2',
            field=models.CharField(db_column='factor_Q2', default=0, help_text='Значения правильных ответов по фактору - Q2.', max_length=2, verbose_name='Значения правильных ответов по фактору - Q2:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_Q3',
            field=models.CharField(db_column='factor_Q3', default=0, help_text='Значения правильных ответов по фактору - Q3.', max_length=2, verbose_name='Значения правильных ответов по фактору - Q3:'),
        ),
        migrations.AddField(
            model_name='kettellquestion',
            name='factor_Q4',
            field=models.CharField(db_column='factor_Q4', default=0, help_text='Значения правильных ответов по фактору - Q4.', max_length=2, verbose_name='Значения правильных ответов по фактору - Q4:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='first_name',
            field=models.CharField(db_column='first_name', default='', help_text='Имя.', max_length=20, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='last_name',
            field=models.CharField(db_column='last_name', default='', help_text='Фамилия.', max_length=20, verbose_name='Фамилия:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='patronymic',
            field=models.CharField(db_column='patronymic', default='', help_text='Отчество.', max_length=20, verbose_name='Отчество:'),
        ),
    ]
