# Generated by Django 3.1.5 on 2021-03-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_auto_20210308_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kettellquestion',
            old_name='answer_1',
            new_name='answer_a',
        ),
        migrations.RenameField(
            model_name='kettellquestion',
            old_name='answer_2',
            new_name='answer_b',
        ),
        migrations.RenameField(
            model_name='kettellquestion',
            old_name='answer_3',
            new_name='answer_c',
        ),
    ]
