# Generated by Django 3.1.5 on 2021-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20210309_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtestuser',
            name='piq',
            field=models.IntegerField(choices=[(1, 'ПВК 1'), (2, 'ПВК 2'), (3, 'ПВК 3'), (4, 'ПВК 4'), (5, 'ПВК 5'), (6, 'ПВК 6'), (7, 'ПВК 7'), (8, 'ПВК 8')], db_column='piq', default=8, help_text='Уровень ПВК.', verbose_name='Уровень ПВК:'),
        ),
    ]
