# Generated by Django 3.1.5 on 2021-04-10 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_informationtestuser_piq'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationtestuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
