# Generated by Django 3.1.5 on 2021-04-12 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_informationtestuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationtestuser',
            name='piq',
            field=models.IntegerField(choices=[(0, 'Общий'), (3, 'ПВК III'), (4, 'ПВК IV'), (5, 'ПВК V'), (6, 'ПВК VI'), (7, 'ПВК VII')], db_column='piq', default=0, help_text='Уровень ПВК.', verbose_name='Уровень ПВК:'),
        ),
        migrations.AlterField(
            model_name='informationtestuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID пользователя.', verbose_name='UUID пользователя:'),
        ),
    ]
