# Generated by Django 3.1.5 on 2021-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_auto_20210412_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='kettellanswer',
            name='report',
            field=models.FileField(blank=True, db_column='report', help_text='DOCX результат обработки ответов.', upload_to='docx/', verbose_name='DOCX результат обработки ответов:'),
        ),
        migrations.AddField(
            model_name='mmpianswer',
            name='report',
            field=models.FileField(blank=True, db_column='report', help_text='DOCX результат обработки ответов.', upload_to='docx/', verbose_name='DOCX результат обработки ответов:'),
        ),
        migrations.AddField(
            model_name='rpmanswer',
            name='report',
            field=models.FileField(blank=True, db_column='report', help_text='DOCX результат обработки ответов.', upload_to='docx/', verbose_name='DOCX результат обработки ответов:'),
        ),
        migrations.AddField(
            model_name='sclanswer',
            name='report',
            field=models.FileField(blank=True, db_column='report', help_text='DOCX результат обработки ответов.', upload_to='docx/', verbose_name='DOCX результат обработки ответов:'),
        ),
        migrations.AddField(
            model_name='tsafetyanswer',
            name='report',
            field=models.FileField(blank=True, db_column='report', help_text='DOCX результат обработки ответов.', upload_to='docx/', verbose_name='DOCX результат обработки ответов:'),
        ),
    ]
